### ISSUE TITLE
array_key_exists() expects parameter 2 to be array / Line 352

### ISSUE THREAD

**Issue by sekru1** [BlowbackDesign/EmailObfuscation#11]
I get the following error message when I view a page with an email address:
PHP Warning: array_key_exists() expects parameter 2 to be array, null given in ..../site\modules\EmailObfuscation\EmailObfuscation.module:352

No selected Templates and no selected Pages in module config.

**Comment by Roope** [comment]
This is now fixed in 578736eb572ec933dd5ec7c7000a86926e686435.
Thanks!
